#!/bin/bash

cd ./files

array1=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
array2=(A B C D E F G H I J K L M N O P Q R S T U V W X Y Z)
for i in ${!array1[@]}
do mv ${array1[i]}* ../${array1[i]}
mv ${array2[i]}* ../${array1[i]}
done
